### ISSUE TITLE
Getting error on uploaded build of angular on server

### ISSUE THREAD

**Issue by prateek756** [Borewit/music-metadata-browser#288] opened 2020-07-15 11:22 UTC
Hi, 

I have integrated **music-metadata-browser** in my **Angular 8** project and its working fine on local server of my system but when I uploaded the project on server then getting error on the component in which **music-metadata-browser** is used. Error that I am getting is: 

**core.js:6014 ERROR Error: Uncaught (in promise): TypeError: Class extends value undefined is not a constructor or null
TypeError: Class extends value undefined is not a constructor or null
    at Object../node_modules/music-metadata/lib/id3v2/ID3Stream.js (ID3Stream.js:8)
    at __webpack_require__ (bootstrap:84)
    at Object../node_modules/music-metadata/lib/aiff/AiffParser.js (AiffParser.js:12)
    at __webpack_require__ (bootstrap:84)
    at Object../node_modules/music-metadata/lib/ParserFactory.js (ParserFactory.js:9)
    at __webpack_require__ (bootstrap:84)
    at Object../node_modules/music-metadata/lib/core.js (core.js:5)
    at __webpack_require__ (bootstrap:84)
    at Object../node_modules/music-metadata-browser/lib/index.js (index.js:5)**

**Comment by Borewit** [comment] 2020-08-03 07:52
The problem seems to be dependency in [ID3Stream](https://github.com/Borewit/music-metadata/blob/master/lib/id3v2/ID3Stream.ts) to Node stream, which is a Node thing. I guess in a lot of cases this is poly-filled, but it does not work here.

I need to investigate a bit further. Maybe I can get rid of the dependency.

**Comment by Borewit** [comment] 2020-08-09 10:37
@prateek756 can you please verify if the issue is resolved with version [v2.1.1](https://github.com/Borewit/music-metadata-browser/releases/tag/v2.1.1)?

**Closed** 2020-10-31 13:37 UTC
