### ISSUE TITLE
Polyfill required with Vite 4 - Buffer is not defined

### ISSUE THREAD

**Issue by not-matt** [Borewit/music-metadata-browser#952] opened 2024-05-15 08:26 UTC
Thanks for your work on this library. This isn't necessarily an issue with this library but worth documenting.

Leaving this here in case it helps anyone in future.

``` console
ReferenceError: Buffer is not defined
    MpegParser MpegParser.js:218
```

To fix, I used [vite-plugin-node-polyfills](https://www.npmjs.com/package/vite-plugin-node-polyfills)

My vite config:

``` ts
import { defineConfig } from "vite";
import { svelte } from "@sveltejs/vite-plugin-svelte";
import { nodePolyfills } from "vite-plugin-node-polyfills";

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [nodePolyfills(), svelte()],

  resolve: {
    alias: {
      src: "/src"
    }
  }
});
```

**Comment by Borewit** [comment] 2024-06-28 10:12
Maybe get rid of Buffer Borewit/token-types#650

Duplicate of #417, and probably many more complains about difficulties poly-filling Node Buffer

**Closed** 2024-06-28 10:12 UTC
Labels: duplicate

**Comment by Borewit** [comment] 2024-07-11 12:43
You may try [music-metadata  ≥ 9](https://github.com/Borewit/music-metadata) , which is guaranteed Buffer free.
