### ISSUE TITLE
check if ReadbaleStream is locked before cancel

### ISSUE THREAD

**Issue by industral** [Borewit/music-metadata-browser#16] opened 2019-04-18 17:40 UTC
got errors in console that ReadableStream is locked, and can't be canceled

**Comment by Borewit** [comment] 2019-04-29 19:26
Related PR: #17

**Comment by Borewit** [comment] 2019-04-30 18:12
Handling cancellation improved in [v0.9.0](https://github.com/Borewit/music-metadata-browser/releases/tag/v0.9.0),

**Comment by Borewit** [comment] 2019-05-01 17:34
Not entirely solved yet, it now throws a `Cannot release a readable stream reader when it still has outstanding read() calls that have not yet settled` exception.

Apparently it is only possible to [release] (https://developer.mozilla.org/en-US/docs/Web/API/ReadableStreamDefaultReader/releaseLock) if the promise of the [read](https://developer.mozilla.org/en-US/docs/Web/API/ReadableStreamDefaultReader/read) has been resolved *and* the resolved function has completed.

**Comment by Borewit** [comment] 2019-05-01 17:51
Fix released in: [v0.9.1](https://github.com/Borewit/music-metadata-browser/releases/tag/v0.9.1)

**Comment by Borewit** [comment] 2019-05-03 17:22
Still unstable; blocked by issue: https://github.com/whatwg/streams/issues/1000

I am releasing the Web-API-readable-stream to Node-readable-stream as [stand alone module](https://github.com/Borewit/readable-web-to-node-stream/i).

And that one has the same issue: Borewit/readable-web-to-node-stream#1

**Closed** 2019-05-04 17:37 UTC

**Comment by Borewit** [comment] 2019-05-04 17:46
Fixed in [v0.10.0](https://github.com/Borewit/music-metadata-browser/releases/tag/v0.10.0).

In BrowserStack there is still an issue on FireFox v66 / Windows 10. Locally I could not reproduce the issue.
